testing: &testing
  hostname: 35.178.101.234
  user: ubuntu
  port: 22
  identityFile: ~/.ssh/deploy.pem
  forwardAgent: false
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: testing
  roles:
    - app
  deploy_path: /mnt/app/testing

production:
  << : *testing
  deploy_path: /mnt/app/production
  stage: production