<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Game;

class InfoPagesController extends Controller
{

    public function __construct()
    {
        $this->facebook = 'https://www.facebook.com/GenieGaming';
        $this->instagram = 'https://www.instagram.com/genieGaming_/';
        $this->twitter = 'https://twitter.com/geniegaming_';
    }

    /**
     * Show the homepage.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {

        $data = [];
        return false;
    }

    public function rules()
    {

        $content = "
        
            <h3>What are the rules and guidelines for 8 Ball Pool Real Cash by Genie Gaming</h3>
            <p><br />Please find below the rules and guidelines for 8 Ball Pool Real Cash.<br />&nbsp;<br /><strong>1. Object of the game of 8-ball Pool Real Cash by Genie Gaming</strong><br />Eight-ball is a pocket billiard game played with 15 object balls and a cue ball.</p>
            <p>To win a game of 8-ball Pool Real Cash, a player must legally pocket the eight ball after potting all of there Balls (Stripes or Solids).</p>
            <p><strong>2. Winner of the Break</strong><br />Player to break in first match is chosen randomly, then the player to break is chosen in a turn based manner.</p>
            <p><strong>3. Racking the Balls</strong><br />The 15 balls are racked in a triangle shape with the foremost ball being any ball except the eight. The order of the balls should be random with the exception of the eight ball which is placed in the middle of the third row, and the two back corner balls which are a stripe and a solid respectively.</p>
            <p><strong>4. The Break</strong><br />ANY break is considered legal as long as the object balls are touched.<br />If none of the object balls are touched, the opponent has ball in hand and then can break from any position on the table.&nbsp;</p>
            <p>a. Potting the 8-ball on the break - If the 8 ball is pocketed on the break, this is NOT a Win of the game.&nbsp;<br />The 8 ball is automatically reset to it's original position.&nbsp;<br />If the 8 ball is pocketed on the break and the cue ball scratches the opponent has ball in hand.</p>
            <p>b. Open table after break - Regardless of how many solids or striped balls are potted on the break, the table is open after the break.<br />&nbsp;In an open table situation, any ball but the 8 ball can be hit first in any combination shot.&nbsp;<br />Once solids or stripes are determined for a player, only their respective balls (solids or stripes) can be struck first in a combination shot.<br />&nbsp;The 8 ball can be used in any combination shot, just not struck first.</p>
            <p>c. Foul on break - If a player Fouls on the break, the opponent has ball in hand.</p>
            <p>d. Breaking - when Breaking The cue ball can be placed anywhere to the left of the Centre-line.</p>
            <p><strong>5. Call pocket on 8 Ball&nbsp;</strong><br />You must pot the 8 Ball in the chosen pocket.<br />(if 8 Ball is potted in any other pocket other than the chosen pocket, this will result in the opponent winning the game)</p>
            <p><strong>6. Call pocket on all shots&nbsp;</strong><br />You must pot the 8 Ball &amp; all of your balls into the chosen pockets.</p>
            <p>Losing<br />(Potting the 8 Ball before potting all of your own Balls will result in opponent winning)<br />(Potting the 8 Ball &amp; the Cue Ball together will result in opponent winning)<br />(Potting the 8 Ball into any other pocket other than the chosen pocket will result in opponent winning)</p>
            <p>Foul&nbsp;<br />(Any of your balls enter a different pocket other than the chosen pocket first, will result in opponent having Ball in Hand)</p>
            <p><strong>7. Legal Shot</strong><br />Legal shot after the break occurs when:</p>
            <p>a. The shooter's cue ball touches any numbered ball on the table, on an open table, with the exception of the eight ball, and drives either it or any other ball after contact, or the cue ball to a rail.</p>
            <p>b. The shooter's cue ball touches a numbered ball that corresponds with the shooters ball group (solids or stripes), once determined, before hitting any other ball, and driving any ball or the cue ball to a rail thereafter, or pocketing any ball except the eight ball (unless player is on the eight ball).</p>
            <p>c. If an object ball is frozen to a rail and is the intended ball on which to make a legal hit, the cue ball must either strike a rail after making contact with the frozen ball, or the frozen ball must contact a different rail.</p>
            <p>Any failure to perform a legal shot is a foul and cue ball in hand is awarded to the incoming player.</p>
            <p><strong>8. Playing</strong><br />A player continues to play until he fails to pocket a ball that corresponds to his ball group, ie Stripes or Solids (or any numbered ball but the eight Ball on an open table) or the eight ball once all of there ball group has been completely pocketed, ie Stripes or Solids or until a foul has been committed.</p>
            <p><strong>9. End of Inning</strong><br />If a player fails to pocket a ball on a legal shot, that player's inning ends and the opponent takes the table where the balls lie. <br />If it is a foul that ends the player's inning, the incoming player is awarded cue ball in hand.</p>
            <p><strong>10. Fouls&nbsp;</strong><br />All fouls result in the opponent of the player who committed the foul being awarded cue ball in hand.&nbsp;<br />The following are fouls:</p>
            <p>a. All ball fouls- if a player touches any other ball with the cue Ball other than there Ball (Stripes or Solids)&nbsp;Once solids or stripes are determined this is&nbsp;a foul &amp; opponent has Ball in Hand.<br />(see section 7)</p>
            <p>b. Potting the Cue ball.</p>
            <p>c. A player fails to shoot before the timer runs out.</p>
            <p>d. A player shoots and fails to hit any balls.</p>
            <p><strong>11. Winning a Game</strong><br />A player wins a game by legally pocketing the eight ball after potting all of there Balls Stripes or Solids.<br />Potting the 8 ball after potting all there corresponding balls (Stripes or Solids).</p>
            <p><strong>12. Losing a Game</strong><br />A player loses a game by committing any foul on a shot that results in the eight ball being pocketed (see section 13) for guidelines on playing the eight ball) or pocketing the eight ball prematurely.</p>
            <p><strong>13. Playing the Eight Ball</strong><br />When playing the eight ball:</p>
            <p>a. The eight ball must always be the first ball contacted by the cue ball, and it or any other ball including the cue ball must contact a rail after the initial hit.&nbsp;<br />Failure to do this is a foul and the opponent is awarded cue ball in hand, it is not a loss of the game.</p>
            <p>b. Combinations, kisses, if the Player is on the Eight Ball - potting opponents Ball (Stripe or Solid)&nbsp;with the Eight Ball&nbsp;are&nbsp;all legal as long as the eight ball is the first ball contacted by the cue ball the &ldquo;Player Wins&rdquo;<br />c. If a player pots the cue ball while playing the eight ball, &amp; the Eight Ball remains on the table this is NOT a loss of the game, opponent&nbsp;has Ball in Hand.<br />Unless the eight ball goes in with the Cue Ball, opponent&nbsp;Wins<br />Not making a legal hit on the eight ball is a Ball in Hand, not an automatic loss of the game.</p>
            <p><strong>14. Illegally Pocketed Balls</strong><br />All balls that are illegally pocketed stay 'down,' with the exception of the eight ball which will result in Losing the game for the shooter.</p>

            <h3>What are the rules and guidelines for 9 Ball Pool Real Cash by Genie Gaming</h3>
            <p>Please find below the rules and guidelines for 9 Ball Pool Real Cash.<br />&nbsp;<br /><strong>1. Object of the game of 9-ball Pool Real Cash by Genie Gaming</strong><br />Nine-ball is a pocket billiard game played with 9 object balls and a cue ball.</p>
            <p>To win a game of 9-ball Pool Real Cash, a player must legally pocket the Nine ball after potting all the lowest numbered Balls (highlighted) First.</p>
            <p><strong>2. Winner of the Break</strong><br />Player to break in first match is chosen randomly, then the player to break is chosen in a turn based manner.</p>
            <p><strong>3. Racking the Balls</strong><br />The 9 balls are racked in a Diamond shape with the foremost ball being the lowest number ball (yellow Ball number 1).</p>
            <p>The order of the balls are random with the exception of the Nine ball which is placed in the middle of the third row.</p>
            <p><strong>4. The Break</strong><br />ANY break is considered legal as long as the lowest numbered Ball is touched first.<br />If the lowest numbered Ball is not touched first the opponent has ball in hand and then can take there shot from any position on the table.&nbsp;</p>
            <p>a. Potting the 9- ball on the break - If the 9 ball is pocketed on the break, this is an Automatic Win of the game.&nbsp;<br />If the 9 Ball is pocketed on the break and the cue ball scratches the 9 Ball is Respotted &amp; the opponent has ball in hand.</p>
            <p>b. You can pot any Ball Legally as long as the Cue Ball hits the lowest numbered Ball first.<br />&nbsp;The 9 Ball can be used in any combination shot, just not struck first, unless&nbsp;Nine Ball is the only Remaining Ball.</p>
            <p>c. Foul on break - If a player Fouls on the break, the opponent has ball in hand.</p>
            <p>d. Breaking,&nbsp;<br />when Breaking The cue ball can be placed anywhere to the left of the Centre-line.</p>
            <p><strong>5. Call pocket on 9 Ball&nbsp;</strong><br />You must pot the 9 Ball in the chosen pocket.<br />(if the 9 Ball is potted in any other pocket other than the chosen pocket, this will result in Nine Ball being respotted &amp; the opponent having Ball in Hand)</p>
            <p><strong>6. Call pocket on all shots&nbsp;</strong><br />You must pot the 9 Ball &amp; all of your balls into the chosen pockets.</p>
            <p>Foul shot.</p>
            <p>First hit is not on the lowest numbered Ball which is (highlighted)</p>
            <p>(Potting the 9 Ball &amp; the Cue Ball together will result in the 9 Ball being respotted &amp; opponent having Ball in Hand)</p>
            <p>(Any of your balls enter a different pocket other than the chosen pocket first, will result in opponent having Ball in Hand)</p>
            <p>Winning</p>
            <p>Potting the 9 Ball after all the other Balls have been potted. <br />Or pot the 9 Ball after after hitting the lowest number Ball first.</p>
            <p><strong>7. Legal Shot.</strong><br />Legal shot after the break occurs when:</p>
            <p>a. The shooter's cue ball touches the lowest numbered ball (highlighted) on the table first&nbsp;and drives either it or any other ball after contact to a rail.</p>
            <p>b. The shooter's cue ball touches the lowest numbered ball first (highlighted)&nbsp;before hitting any other ball, and driving any ball or the cue ball to a rail thereafter.</p>
            <p>c. If the object ball is frozen to a rail and is the intended ball on which to make a legal hit, the cue ball must either strike a rail after making contact with the frozen ball, or the frozen ball must contact a different rail.</p>
            <p>Any failure to perform a legal shot is a foul and cue ball in hand is awarded to the incoming player.</p>
            <p><strong>8. Playing</strong><br />A player continues to play until he fails to pocket a ball.<br />You can continue playing legally by potting any Ball as long as the Cue Ball hits the lowest numbered Ball first.</p>
            <p><strong>9. End of Inning</strong><br />If a player fails to pocket a ball on a legal shot, that player's inning ends and the opponent takes the table where the balls lie.<br />If it is a foul that ends the player's inning, the incoming player is awarded cue ball in hand.</p>
            <p><strong>10. Fouls&nbsp;</strong><br />All fouls result in the opponent of the player who committed the foul being awarded cue ball in hand.&nbsp;</p>
            <p>The following are fouls:</p>
            <p>a. All ball fouls- if a player touches any ball other than the lowest numbered Ball first (highlighted) is then a foul shot.<br />Which will result in opponent having Ball in Hand.</p>
            <p>(see section 7)</p>
            <p>b. Potting the Cue ball.</p>
            <p>c. A player fails to shoot before the timer runs out.</p>
            <p>d. A player shoots and fails to hit any balls.</p>
            <p><strong>11. Winning a Game</strong><br />A player wins a game by legally pocketing the Nine ball after all the other Balls have been potted.<br />Or pot the Nine Ball after hitting the lowest numbered Ball first (highlighted).</p>
            <p><strong>12. Losing a Game</strong><br />A player loses a game by there opponent potting the Nine Ball after all the other Balls have been potted.<br />Or opponent pots the Nine Ball after hitting the lowest numbered Ball first.</p>
            <p><strong>13. Playing the Nine Ball</strong><br />When playing the Nine ball:</p>
            <p>a. The Nine ball must always be the first ball contacted by the cue ball, and it must contact a rail after the initial hit.&nbsp;<br />Failure to do this is a foul and the opponent is awarded cue ball in hand, it is not a loss of the game.</p>
            <p>b. Pots from Combinations, kisses, are all legal as long as the lowest number Ball (highlighted) is the first ball contacted by the cue ball.</p>
            <p>c. If a player pots the cue ball &amp; the Nine Ball together while playing the Nine ball,<br />it is NOT a loss of the game.<br />The&nbsp;Nine Ball is respotted &amp; opponent has Ball in Hand.<br />Not making a legal hit on the Nine ball is a Ball in Hand, not an automatic loss of the game.</p>
            <p><strong>14. Pocketed Balls</strong><br />All balls that are pocketed stay 'down,' with the exception of the Nine ball if the lowest numbered Ball (highlighted) was not the first Ball hit which will result in the Nine Ball being respotted &amp; opponent having Ball in Hand.</p>

        ";

        $data = [
            'content' => $content,
            'facebook' => $this->facebook,
            'instagram' => $this->instagram,
            'twitter' => $this->twitter,
        ];

        return view('pages.info', $data);
    }

    public function privacyPolicy()
    {

        $content = "
           


            <h2>Privacy Policy</h2>
            <p>Updated Jan 2019</p>
            <p>This Privacy Policy Statement (&ldquo;Privacy Policy&rdquo;) is applicable to users who download the application connecting to this Privacy Policy (the &ldquo;Application&rdquo;) and all services provided thereon (&ldquo;Services&rdquo;), including all Genie Gaming Public Forums (as defined in the <a href='https://geniegaming.com/terms-and-conditions'>Terms of Service</a>). This Privacy Policy does not cover any interaction you may have with Genie Gaming by telephone, postal mail, or other offline communications.</p>
            <h3>Notice</h3>
            <p>Genie Gaming respects your privacy and is committed to protecting personal information that you provide in connection with your use of the Services. This Privacy Policy is intended to provide you notice of the Company&rsquo;s information practices, including the types of information gathered, how information is used and safeguarded, and how you may control the maintenance and sharing of your information.</p>
            <p>BY downloading the Application and USING THE SERVICES, YOU CONSENT TO THE TERMS AND CONDITIONS OF THIS PRIVACY POLICY AND TO OUR PROCESSING OF PERSONAL INFORMATION FOR THE PURPOSES STATED BELOW. IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS OF THIS PRIVACY POLICY, PLEASE do not download the Application and DO NOT USE THE SERVICES.</p>
            <h3>Collection of Personally Identifiable Information and Other Data</h3>
            <p>To register an account with Genie Gaming, you must provide an email address and password, and verify that you are over the age of 18. Genie Gaming will also permit you to choose a username. Please note that your username will be available to the other Genie Gaming users while you participate in tournaments and public forums. Your username, name, password and email address are collectively referred to as your &ldquo;Account Information&rdquo;.</p>
            <p>Your personal profile will automatically be populated with your selected username, which you are allowed to change. Any information and content that you voluntarily add to your profile, such as your personal image, will be made public by default and will not be subject to this policy. Your username and profile will be publicly searchable, and your personal image will appear in search results in addition to your profile.</p>
            <p>Should you choose to participate in Genie Gaming cash tournaments, we will ask you to submit your credit card information or your Paypal user name. To participate in cash tournaments and withdraw funds, we also require that you provide certain personally identifiable information, including your first and last name, billing address and phone number (your &ldquo;Personally Identifiable Information&rdquo;). Your Personally Identifiable Information is used to verify your identity when you withdraw cash from your account and by us and certain third party service providers to monitor for fraudulent activity and verify that you can legally participate in cash tournaments and withdraw funds. By providing Personally Identifiable Information, you represent to us that it is accurate and complete, and agree to promptly update the information as necessary to ensure that your Personally Identifiable Information remains current. We reserve the right to terminate your access to the Services if for any reason we suspect that you have provided inaccurate Personally Identifiable Information. You should carefully review our <a href='https://geniegaming.com/terms-and-conditions'>Terms of Service</a> because they include an agreement from you to indemnify and hold Genie Gaming not liable for any losses that result from you providing inaccurate Personally Identifiable Information.</p>
            <p>Genie Gaming want to give you the most exciting gaming experience possible. To help us figure out what you like and dislike about our Services, we may ask for your opinion from time to time. Genie Gaming may request and/or collect information from you on a voluntary basis when you:</p>
            <ul>
            <li>Create an account with the Services</li>
            <li>Withdraw or deposit cash from your account*</li>
            <li>Enter a shipping and billing address to withdraw cash from your account</li>
            <li>Participate in contests, events, or promotions</li>
            <li>Send questions or comments to our support team</li>
            <li>Submit your resume to us online</li>
            <li>Fill out online surveys</li>
            </ul>
            <p>*Genie Gaming will use third party credit card processing companies to process your transactions. When using a third party processing company, Genie Gaming will not have access to your credit card data.</p>
            <p>Genie Gaming may also use technology, such as cookies, transparent gifs, frames, server log analysis and other technologies as they are developed, to enhance your experience with the Services. We automatically collect certain aggregate information and analytical data related to your Application usage. Aggregate information is non-personally identifiable or anonymous information about you, including the date and time of your visit, the phone network associated with your mobile device, your mobile device&rsquo;s operating system or platform, the type of mobile device you use, your mobile device&rsquo;s unique device ID and the features of our Application which you accessed.</p>
            <p>With your consent and in connection with your use the Application, we may use GPS technology (or other similar technology) to determine your current location in order to determine the state you are located within to establish which aspects of the Services you are permitted to use. You may withdraw your consent to our collection of your location information at any time, provided that you are not participating in cash competitions. If you choose to participate in a cash competition, you may not opt out of the collection of this type of geolocation data.</p>
            <p>We urge you to keep your password confidential and refrain from sharing it with others. Genie Gaming will not disclose, share, sell or rent Personally Identifiable Information to any third party without your prior consent.</p>
            <h3>Special Notice Regarding Minors Under 18 Years of Age</h3>
            <p>Genie Gaming respect the privacy of children of all ages. Genie Gaming particularly recognizes the sensitivity of personal information concerning minors under the age of 18 and therefore provides this special notice to parents and guardians regarding the collection and use of information collected from minors in this age group.</p>
            <p>The Services are not directed towards young children or minors under the age of 18. Genie Gaming are intent on complying with applicable laws and regulations regarding minors, Specifically, Genie Gaming will not knowingly collect and maintain any personally identifiable information from children under 18.</p>
            <p>If you are a parent or guardian who has discovered that your child has submitted his or her personal information, Genie Gaming will make reasonable efforts to delete the information from its database, at your request. To request the deletion of your child&rsquo;s information, please send an email <a href='mailto:support@geniegaming.com'>support@geniegaming.com</a>. Be sure to include in your message the username, email address and password that your child submitted.</p>
            <h3>Use of Information Collected</h3>
            <p>Except as specifically outlined in this Privacy Policy, we do not share your Personally Identifiable Information or Account Information with non-affiliated third parties without your permission. We may disclose Personally Identifiable Information, aggregated information, such as demographic information, and certain statistical analysis to third party service providers to ensure compliance with applicable laws and monitor for fraudulent activity, and to third party developers who are reviewing or auditing our Services. However, before sharing your information with any such third party, we require that the third party enter into an agreement that requires that third party to keep your information confidential, and prohibits that third party from using your information for any purpose that is not related to the Services.</p>
            <p>We disclose information, including Personally Identifiable Information, that we, in good faith, believe is appropriate to cooperate in investigations of fraud or other illegal activity, or to conduct investigations of violations of our Terms of Service. For example, this means that if we conduct a fraud investigation and conclude that one side has engaged in deceptive practices, we can give that person or entity&rsquo;s contact information to victims who request it.</p>
            <p>We disclose information, including Personally Identifiable Information, in response to a summons, warrant, court order, levy, attachment, order of a court-appointed receiver or other comparable legal process. If the summons seeks information about an identified user or limited group of users, we&rsquo;ll make reasonable business efforts to contact the user(s) before providing information to the party that requests it. We cannot guarantee that we will be able to contact the user(s) in all cases, whether because of a time limit, court order, inability to effectively contact a user, or for any other reason.</p>
            <p>By upgrading an account and providing an email address, users authorise Genie Gaming to provide them with important announcements, relevant promotions, and other related communications. Users will always have the opportunity to opt out of these communications at any time.</p>
            <p>Your Account Information and certain Personally Identifiable Information is transmitted to a third-party service provider for the purpose of processing any payments. The transmission of your payment information is automatic, and at no point do we, or any of our agents or employees, have the ability to review, access or retain such payment information.</p>
            <p>Except as set forth herein, Genie Gaming do not sell, rent, or otherwise disclose Personally Identifiable Information collected from and about its users to third parties. However, in the event of a merger, acquisition, reorganisation, bankruptcy, or other similar event, Genie Gaming&rsquo;s customer information may be transferred to Genie Gaming&rsquo;s successor or assign, if permitted by and done in accordance with applicable law.</p>
            <h3>Use of Cache Data</h3>
            <p>A cache is a component of your mobile device that transparently stores data for record-keeping purposes. Cache data does not identify users, but does identify your mobile device. Most browsers and applications are initially set up to accept such data. If you prefer, you can program your mobile device so that it does not store this information while utilising the Application. Certain Application features may only be available through the collection of such data. We may use such data to assist in data collection and to track Application usage and trends to help us better serve you. We also permit third parties who have entered into confidentiality agreements to access such data to help us monitor use of the Application for fraud or any other activity that does not comply with applicable laws.</p>
            <p>Some of our business partners (e.g., analytical tracking software providers) use cookies and tracking technologies on the Application. We have no access to or control over these cookies or tracking technologies. This Privacy Policy covers the use of cookies and cache data on the Application and by us only and does not cover the use of cookies or tracking technologies by any such business partner.</p>
            <h3>Account Security</h3>
            <p>The security of your account relies on your protection of your password and mobile device. You are responsible for maintaining the security of your password and mobile device. You are solely responsible for any and all activities that occur under your account. You may not share your password or the Application with anyone. We will never ask you to send your password or other sensitive information to us in an email, though we may ask you to enter this type of information on the Application interface.</p>
            <p>Any email or other communication requesting your password or asking you to provide sensitive account information via email should be treated as unauthorized and suspicious and should be reported to us immediately at <a href='mailto:support@geniegaming.com'>support@geniegaming.com</a>. If you do share your password or your mobile device with a third party for any reason, the third party will have access to your account and your personal information, and you may be responsible for actions taken using your password. If you believe someone else has obtained access to your password, please change it immediately. If you believe that an unauthorized access has already occurred please report it immediately at <a href='mailto:support@geniegaming.com'>support@geniegaming.com</a>.</p>
            <p>We may have access to your password and may use such password to access your account for debugging, quality assurance, or other internal purposes.</p>
            <h3>Postings to Public Forums</h3>
            <p>All postings in Genie Gaming public forums will generally be available to, and freely accessible by, other users of the Genie Gaming public forums as well as the Internet general public. Therefore, users should not expect that any information they post will be kept private or confidential and are encouraged to exercise discretion when using the public forums. Additionally, your username, which you can change, will always be included in conjunction with your postings in the public forums. Genie Gaming are not responsible for events arising from the distribution of any information you choose to publicly post or share through the forums. All information or materials uploaded by you while utilizing the Services is subject to our <a href='https://geniegaming.com/terms-and-conditions'>Terms of Service</a>.</p>
            <h3>Maintaining and Updating Your Account Information</h3>
            <p>As part of your use of the Services, you are responsible for maintaining and updating, as applicable, your Account Information with current and complete information. You may edit and delete portions of your Account Information. To do this, select &ldquo;My Account&rdquo; in the main menu and choose which information to edit or delete. You can also delete your Genie Gaming Account entirely. To do this, email us at <a href='mailto:support@geniegaming.com'>support@geniegaming.com</a> and request for your account to be deleted. Be sure to include in your message the username, email address and password for your account to be deleted.</p>
            <p>After receiving any requested changes to your Account Information or Personally Identifiable Information, we will make reasonable efforts to ensure that all of your personal information stored in databases we actively use to operate the Services will be updated, corrected, changed, or deleted as appropriate, as soon as reasonably practicable. However, we reserve the right to retain in our archival files any information we remove from or change in our active databases. We may retain such information to resolve disputes, troubleshoot problems, and enforce our <a href='https://geniegaming.com/terms-and-conditions'>Terms of Service</a>. In addition, it may not be technologically possible to remove every record of the information you have previously provided us, as a copy may exist in a non-erasable form that will be difficult or impossible for us to locate.</p>
            <p>If you are the parent or guardian of a child under the age of 18, and you have discovered that your child created an account and would like to have it deleted, please e-mail us <a href='mailto:support@geniegaming.com'>support@geniegaming.com</a> with your child&rsquo;s username, email address and password.</p>
            <h3>Effective Date; Policy Changes</h3>
            <p>Each time you use the Application, the current version of the Privacy Policy will apply. Accordingly, when you use the Application, you should check the date of this Privacy Policy (which appears at the top of the Privacy Policy) and review any changes since the last version. Our business changes frequently and this Privacy Policy is subject to change from time to time. Unless stated otherwise, our current Privacy Policy applies to all information that we have about you. We will not materially change our policies and practices to make them less protective of customer information collected in the past without the consent of affected customers.</p>
            <h3>Contact Us</h3>
            <p>To contact us with your questions or comments regarding this Privacy Policy or the information collection and dissemination practices of the Application, please email us at <a href='mailto:support@geniegaming.com'>support@geniegaming.com</a></p>
        ";

        $data = [
            'content' => $content,
            'facebook' => $this->facebook,
            'instagram' => $this->instagram,
            'twitter' => $this->twitter,
        ];

        return view('pages.info', $data);
    }

    public function termsAndConditions()
    {

        $content = "
            
            <h2>Terms & Conditions</h2>
            <p><strong>Revised Jan 2019 </strong></p>

            <p>Revisions</p>
            <p>3.3.2 Prohibition from participating in skill based gaming.</p>
            <p>3.4 Additional identification and proof of income required to access certain stages in game.</p>
            <p>4.10 Advice on dormant accounts/account inactivity.</p>
            <p>5.9 Maximum account balance.</p>
            <p>5.10 &lsquo;Friends&rsquo; feature, limiting amount of game play in any 24 hour period.</p>
            <p><strong>END-USER TERMS AND CONDITIONS OF SERVICE </strong></p>
            <p><strong>IMPORTANT </strong></p>
            <p><strong>THIS APPLICATION IS OPERATING THE GAMING SOFTWARE OF [UNITY TECHNOLOGIES ApS (&ldquo;UNITY&rdquo;) AS LICENSED TO ROBERT EDGAR]. A CONDITION TO YOUR DOWNLOADING OR OTHERWISE USING THE SOFTWARE (AS DEFINED BELOW) IS THAT YOU ENTER INTO THE FOLLOWING LEGALLY BINDING [SUB-LICENSE] AGREEMENT WITH US, WHICH GOVERNS YOUR USE OF THE SOFTWARE. </strong></p>
            <p><strong>PLEASE READ THIS AGREEMENT (AND ALL DOCUMENTS AND INFORMATION IT REFERS TO) CAREFULLY, TO MAKE SURE YOU FULLY UNDERSTAND ITS CONTENT. IF YOU HAVE ANY DOUBTS ABOUT YOUR RIGHTS AND OBLIGATIONS RESULTING FROM THE ACCEPTANCE OF THIS AGREEMENT, PLEASE CONSULT A SOLICTOR OR OTHER LEGAL ADVISOR IN YOUR JURISDICTION. </strong></p>
            <p><strong>IMPORTANT: PERSONS LOCATED IN RESTRICTED TERRITORIES (AS DEFINED BELOW) ARE NOT PERMITTED TO USE THE SOFTWARE IN ANY WAY OR MANNER IN CONNECTION WITH ANY CASH GAMES (AS DEFINED). TO REMOVE ANY DOUBT, THIS RESTRICTION ALSO APPLIES TO RESIDENTS AND CITIZENS OF OTHER NATIONS WHILE LOCATED IN A RESTRICTED TERRITORY. THE FACT THAT THE APPLICATION IS ACCESSIBLE IN A RESTRICTED TERRITORY, OR THAT THE SOFTWARE ALLOWS THE USE OF THE OFFICIAL LANGUAGE OF A RESTRICTED TERRITORY, SHALL NOT BE CONSTRUED AS A LICENSE TO USE THE SOFTWARE IN SUCH RESTRICTED TERRITORY. ANY ATTEMPT TO CIRCUMVENT THIS RESTRICTION, FOR EXAMPLE, BY USING A VPN, PROXY OR SIMILAR SERVICE THAT MASKS OR MANIPULATES THE IDENTIFICATION OF YOUR REAL LOCATION, OR BY OTHERWISE PROVIDING FALSE OR MISLEADING INFORMATION REGARDING YOUR CITIZENSHIP, LOCATION OR PLACE OF RESIDENCE, OR BY ENTERING CASH GAMES USING THE SOFTWARE THROUGH A THIRD PARTY OR ON BEHALF OF A THIRD PARTY LOCATED IN A RESTRICTED TERRITORY IS A BREACH OF THIS AGREEMENT AND MAY CONSTITUTE A CRIMINAL OFFENSE. IF IT BECOMES APPARENT, OR WE HAVE REASONABLE GROUNDS TO SUSPECT, THAT YOU ARE LOCATED IN ANY OF THE RESTRICTED TERRITORIES, THIS MAY RESULT IN CLOSING YOUR PLAYER ACCOUNT, WITHOUT AN OBLIGATION TO PROVIDE YOU WITH ADVANCE NOTICE, FREEZING THE FUNDS THEREIN AND PROVIDING THE APPLICABLE DETAILS TO THE RELEVANT AUTHORITIES, ALL IN ACCORDANCE WITH APPLICABLE LAWS AND AGREEMENTS, AND YOU SHALL BE LIABLE TO US FOR ANY DAMAGE OR LOSS RESULTING THEREFROM. </strong></p>
            <p><strong>BY ACCEPTING THE TERMS AND CONDITIONS (INCLUDING BY TICKING THE &ldquo;I AGREE&rdquo; BOX), YOU (A) AGREE TO THE USE OF ELECTRONIC COMMUNICATIONS IN ORDER TO ENTER INTO CONTRACTS, AND YOU WAIVE ANY RIGHTS OR REQUIREMENTS UNDER APPLICABLE LAWS OR REGULATIONS IN ANY JURISDICTION WHICH REQUIRE AN ORIGINAL (NON-ELECTRONIC) SIGNATURE, TO THE EXTENT PERMITTED UNDER APPLICABLE LAW, YOU (B) ALSO CONFIRM THAT YOU HAVE READ THIS AGREEMENT AND (C) AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS AND (D) YOU CONFIRM YOU ARE AUTHORISED AND ABLE TO ACCEPT THESE TERMS AND CONDITIONS. </strong></p>
            <p><strong>IF YOU DO NOT AGREE WITH ANY OF THE TERMS OF THIS AGREEMENT, DO NOT ACCEPT THE TERMS AND CONDITIONS AND DO NOT CONTINUE TO DOWNLOAD, INSTALL OR OTHERWISE USE THE SOFTWARE.</strong></p>            
            <p>&nbsp;</p>
            <p><strong>END-USER TERMS AND CONDITIONS OF SERVICE: YOUR ATTENTION IS DRAWN SPECIFICALLY TO </strong></p>
            <p><strong>CLAUSE 11 (LIMITATION OF LIABILITY AND INDEMNITY)</strong></p>
            <h3>1. Definitions</h3>
            <p>The definitions and rules of interpretation set out in Schedule 1 shall apply in this Agreement.</p>
            <h3>2. Subject Matter of Agreement</h3>
            <p>Your agreement with us relating to your use of Software, the Application and the Online Games includes this Agreement (including the Privacy Policy and the rules of the Online Games, both of which form part of this Agreement). The rules of the Online Games are placed in the <u><a href='http://www.geniegaming.com/rules'>www.geniegaming.com/rules</a></u> as well as other sections of the Software and the Application, including but not limited to, rules describing how to play the Online Games, and any other rules governing a particular game. All such rules are incorporated and included under the terms of this Agreement.</p>
            <h3>3. The Player</h3>
            <p>3.1. You need to register on the Application in order to play the Online Games. We reserve the right to refuse in our absolute discretion to complete registration for you or any prospective player for any reason.</p>
            <p>3.2. You warrant and represent to us that:</p>
            <p>3.2.1. you are a natural person, are over 18 years old and, in any event, are of legal age as determined by the laws of the country where you are located;</p>
            <p>3.2.2. all information you supply to us is complete, accurate and current (and knowingly submitting incomplete or inaccurate information, or failing to update and maintain current, complete and accurate information, may result, without limitation, in immediate termination of your Player Account;</p>
            <p>3.2.3. you are not colluding or attempting to collude or intending to participate, directly or indirectly, in any collusion scheme with any other player in the course of any game you play or will play;&nbsp;</p>
            <p>3.2.4. you will not use the Application for any commercial activity or on behalf of any other person or persons; and</p>
            <p>3.2.5. you are not bankrupt or subject to any similar proceedings (and such proceedings are not threatened) and you are not in any arrangement or composition with your creditors.</p>
            <p>3.3. If you use the Software in any way or manner in connection with any Cash Games, you warrant and represent to us that:</p>
            <p>3.3.1. you are not a resident of any of the Restricted Territories;&nbsp;</p>
            <p>3.3.2. you are not a person prohibited from participating in remote skill based gaming of the nature provided by the UK governmental body or department in any other country that may now or in the future prohibit persons in a manner similar to the Office of Foreign Assets Control; and</p>
            <p>3.3.3. You have examined the legality of your participation in the Online Games and use of the Software in each jurisdiction that is applicable to you, and have found the same to be legal in such jurisdictions under all Applicable Laws and orders of any competent authority.&nbsp;</p>
            <p>3.4. You may be required to provide the following in the course of registering: name, postal address, date of birth, gender, email address, mobile phone number and their own security questions, (where you play or intend to play in Cash Games) Credit Card/Bank Account number or other method of payment and other information or forms of identification that we may request (including Valid Identification Documents). You expressly acknowledge that a failure to provide any such information may result in us refusing to complete registration of you and any other prospective player. You hereby consent to us carrying out age verification and identity checks and you agree to supply any Valid Identification Document we may request from you. &pound;50 and &pound;100 room access are subject to additional ID/proof of income.</p>
            <p>3.5. Where you deposit funds to play Cash Games, you shall ensure that the Credit Card/Bank Account data provided by you at the point of depositing is accurate and complete, and that their Credit Card has not been lost or stolen or the subject of fraud. You shall immediately inform us: (i) if your Credit Card becomes lost or stolen; or (ii) if you have given away, shared or lost your account number and/or password for your relevant Credit Card/Bank Account or your Username or Password.</p>
            <p>3.6. You shall: (i) fill out all of the compulsory fields in the registration form; (ii) ensure that their data is accurate and complete; and (iii) immediately inform us of any change in the data supplied by them during registration, including changes to Credit Card/Bank Account data, by making the requisite changes to their Player Accounts.</p>
            <p>3.7. We are not responsible for any failure to deliver any Winnings if any information supplied by you required for such delivery is incorrect, incomplete or out of date. We are not under any duty to contact you in order to complete or correct any information that is, or may appear to be, incomplete, incorrect or out of date.</p>
            <h3>4. Account and Password</h3>
            <p>4.1. Once your details are accepted by us for registration as a Player Account, you will be sent an email containing your Username and a link to reset your Password, through which you can access your Player Account on the Application, and carry out deposit and withdrawal transactions on the Player Account.</p>
            <p>4.2. We will determine whether the funds that you have requested to be credited to your Player Account are available. Funds will only be credited to the Player's Account if we are satisfied that your Credit Card has not been reported as lost or stolen and is not the subject of any fraud.</p>
            <p>4.3. If you give Credit Card/Bank Account details relating to a Bank Account held jointly with another person, you both accept that Winnings won by either of you may be paid into that joint account.</p>
            <p>4.4. You must keep your Username and Password secure and take all steps to prevent unauthorised use of these details. You are responsible for all activity conducted through your Player Account. You shall not allow anyone else to use your Password or Username. You are not authorised to use third parties' Passwords or Usernames. You are prohibited from attempting to sell or otherwise transfer the benefit of your Player Account to any third party and you are prohibited from acquiring or trying to acquire a Player Account which has been opened in the name of a third party.&nbsp;</p>
            <p>4.5. It is your obligation to report suspected fraud and illicit use of your Player Account to us, and to take such steps as may be required in order to overcome it, such as by changing the Password on the Player Account. You may change your Password at any time through the relevant Player Account.</p>
            <p>4.6. You are not permitted to have more than one Player Account at any one time. If an additional account or accounts are opened, we will be entitled in its sole discretion to investigate and close any such accounts without notice. If you wish to establish a new Username, you must close your existing Player Account and open a new Player Account under the new Username.</p>
            <p>4.7. We shall be entitled in our sole discretion to set and amend from time to time monetary limits on the operation of Player Accounts, including (without limitation) limits on minimum and maximum deposit amounts, minimum and maximum Prizes and maximum aggregate sums that may be paid to enter a Cash Game in a particular time period.</p>
            <p>4.8. It is open to all potential players to exclude themselves from playing Online Games (including Cash Games), using our self-exclusion facility or by contacting Customer Services by email <a href='mailto:support@geniegaming.com'>support@geniegaming.com</a> By entering into a self-exclusion agreement with us, a Player will be prohibited from using their Player Account and from opening a new Player Account during the selfexclusion period. We will not knowingly permit players that have chosen to self-exclude to reactivate their Player Account or open a new Player Account under any circumstances during the self-exclusion period. After the end of the self-exclusion period, customers may reactivate their Player Account or open a new Player Account and recommence their entering of Online Games by contacting customer services.</p>
            <p>4.9. You may close your Player Account by giving us at least 24 hours' notice (through his/her Player Account on the Application or by email to <a href='mailto:support@geniegaming.com'>support@geniegaming.com</a>, following which we will return any remaining balance from your Player Account (subject to the deduction of entry fees for any Cash Games you have already entered for which you shall remain liable) to the Bank Account / Credit Card, details of which are held by us in respect of you, or return the remaining balance to you by other appropriate means. In the event that we are not able to return the remaining balance to the Bank Account / Credit Card or to you by other appropriate means, it will be treated as unclaimed Winnings in accordance with clause 4.10 below.</p>
            <p>4.10. Should your Player Account become dormant through inactivity, we will contact you to advise of any available Player Account balance. After a dormant period of 30 days your account balance will be refunded to your active payment method. If a player account is dormant for 6 months the account holder will be contacted and the account will be closed.</p>
            <h3>5. Deposits, Winnings and Payments</h3>
            <p>5.1. If you deposit funds to enter Cash Games, you may request a withdrawal of funds from your available Player Account balance at any time. Withdrawal requests will not be processed until you have provided us with such Valid Identification Documents as we may have requested from you. Any digital or virtual asset (whether virtual cash, trophies or otherwise) and Bonus Funds (as defined in Section 5.2) cannot be withdrawn. Processing of requested funds is made by refund to the Card/Bank Account used to make your deposit will generally be completed within three (3) business days although we cannot guarantee this. We may freeze your Player Account and/or delay a request for withdrawal of funds pending completion of any investigation of reported or suspected abuse, verification of eligibility, or to comply with applicable legislation.</p>
            <p>5.2. If you play in a Cash Game at any time, then we may, from time to time in our sole discretion, grant you bonus funds and/or credits ('Bonus Funds'). Bonus Funds can be used to enter Cash Games, but cannot be withdrawn or used for any other service offered by the Application. If you initiate a withdrawal of funds from your Account, you will forfeit all Bonus Funds currently in your Account. If you do not enter a Cash Game within a continuous 30 day time period, all Bonus Funds in your account will be forfeited.</p>
            <p>5.3. If you are eligible to receive Winnings, we may require that you provide us with proof that you are, or were at the time of your participation in the Cash Game, eligible to participate in accordance with this Agreement and that your participation was in accordance with this Agreement. You will also be required to provide such Valid Identification Documents as we may request before being entitled to receive Winnings. If you do not provide us with such proof to our reasonable satisfaction, then you will not receive the relevant Winnings. If you receive a payment in error, we may reverse or require return of the payment.</p>
            <p>5.4. We are not a financial institution and you shall not in any way treat us a financial institution. No interest is paid on any funds deposited, irrespective of the amount held in your Player Account.</p>
            <p>5.5. To comply with the Proceeds of Crime Act 2002 and the Money Laundering Regulations 2007 (Regulations) we must be satisfied that there is no suspicion of money laundering and/or that you are not becoming involved in any of the relevant offences. We reserve the right to check your transactions to prevent money laundering and we reserve the right to report any suspicious transactions to the relevant authorities. We reserve the right to carry out enhanced due diligence on any individual that poses an additional risk (for the purposes of section 14 of the Regulations). Enhanced due diligence may include checking the World Check and/or Politically Exposed Persons databases or mqy involve you supplying such other evidence we require to verify both your identity and the source and flow of any funds you provide in connection with the Services.</p>
            <p>5.6. It is your responsibility to report your Winnings to the applicable taxation and other governmental authorities, if you reside in a jurisdiction where those Winnings are taxable or otherwise subject to deduction by those authorities.</p>
            <p>5.7. You accept that all we are entitled to treat all payments you make to us as being authorised by you and you shall not, in any circumstances, attempt to reverse a payment to avoid a legitimate liability. Any fraudulent use of your Credit Card or other payment method (regardless of the outcome) or failure of you to honour legitimate charges or requests for payment will result in the immediate termination of your Player Account and all sums deposited in connection with that Player Account will be forfeited. ANY SUCH FRAUDULENT ACTIVITY MAY RESULT IN LEGAL PROCEEDINGS AND/OR A REFERRAL TO THE POLICE.</p>
            <p>5.8. Unless otherwise required by law, no refunds are given.</p>
            <p>5.9. A players balance may not exceed &pound;200 at any one time, any winnings taking the balance over this threshold shall be refunded directly to the active payment method used to deposit. You will be notified with an on screen instruction and also by email. A receipt will be shown in your recent transactions.</p>
            <p>5.10. The &lsquo;friends&rsquo; feature will only allow &pound;1 and &pound;2 games to be played and no more than &pound;20 per &lsquo;friend&rsquo; (user) may be staked in any 24 hr period.</p>
            <h3>6. Licence to Use the Software; Restrictions</h3>
            <p>6.1. We hereby grant to you a limited, personal, nontransferable, non-exclusive, worldwide (except as noted below) license to download, access and otherwise utilise the Software on your device, solely in order to play the Online Games, in accordance with this Agreement and solely for as long as your Player Account is active. If you wish to participate in Cash Games, you may need to download additional software from us or a third party such as a game developer. If you do not download the additional software, you will not be able to participate in the Cash Games.</p>
            <p>6.2. This license applies only to the object code of the Software (i.e., the compiled, assembled, or machine executable version of the Software) and does not grant you any rights whatsoever with respect to the source code of the Software.&nbsp;</p>
            <p>6.3. Notwithstanding anything to the contrary herein, persons located in the Restricted Territories are not permitted to use the Software in any way or manner in connection with any Cash Games. To remove any doubt, this restriction also applies to residents and citizens of other nations while located in a Restricted Territory. This license does not apply to, and does not allow you the use of the Software in or from any Restricted Territories, and the fact that the Application is accessible in a Restricted Territory, or that the Software allows the use of the official language of a Restricted Territory, shall not be construed as a license to use the Software in such Restricted Territory. Any attempt to circumvent this restriction, for example, by using a VPN, proxy or similar service that masks or manipulates the identification of your real location, or by otherwise providing false or misleading information regarding your location, citizenship, or place of residence, or by entering Cash Games using the Software through a third party or on behalf of a third party located in a Restricted Territory, is a breach of this agreement and may constitute a criminal offense under Applicable Laws. If it becomes apparent, or we have reasonable grounds to suspect, that you are located in any of the Restricted Territories, this may result in closing your Player Account, without an obligation to provide you with advance notice, freezing the funds therein and providing the applicable details to Unity and/or relevant authorities, all in accordance with Applicable Laws and agreements, and you shall be liable to us for any damage or loss resulting therefrom. IT IS YOUR DUTY TO CONSULT AND CHECK REGULARLY OUR APPLICATION AND/OR OUR WEBSITE REGARDING THE LIST OF THE RESTRICTED TERRITORIES.&nbsp;</p>
            <p>6.4. We reserve any and all rights not expressly granted in Section 6.1 above. In addition, you are not permitted to, and you agree not to permit or assist others to:</p>
            <p>6.4.1. use, copy, modify, create derivative works from or distribute the Software, any part of it, or any copy, adaptation, transcription, or merged portion</p>
            <p>of it;</p>
            <p>6.4.2. decode, reverse engineer, disassemble, decompile or otherwise translate or convert the Software or any part of it;</p>
            <p>6.4.3. transfer, loan, lease, assign, rent, or otherwise sublicense the Software;</p>
            <p>6.4.4. remove any copyright, proprietary or similar notices from the Software (or any copies of it);&nbsp;</p>
            <p>6.4.5. operate the Software or any part of it for the benefit of or on behalf of any third party, including by way of &lsquo;bulletin board&rsquo;, online service or remote dial-in, application service provider services, internet service provider services, timesharing arrangements, outsourcing services or bureau services;&nbsp;</p>
            <p>6.4.6. copy or translate any user documentation provided online or in electronic format;</p>
            <p>6.4.7. enter, access or attempt to enter or access or otherwise bypass our security system or interfere in any way (including but not limited to, robots and similar devices) with Application or attempt to make any changes to the Software and/or any features or components thereof; or</p>
            <p>6.4.8. use any Assistance Programs in connection with the Software and/or the Online Games. you are prohibited from any interaction within the Online Games that is not the direct result of you personally utilizing the Software for the purpose for which it was intended.</p>
            <p>6.5. You acknowledge and agree that we may take steps to detect and prevent the use of Assistance Programs. These steps may include, but are not limited to, examination of software programs running concurrently with the Software on your device. You agree that you will not attempt to bypass, interfere with, or block such steps, including, without limitation, the use of third party software that bypasses, interferes with, or blocks such steps. Any attempt to restrict us in this matter will entitle us to immediately suspend the availability of the Software to you and you shall immediately forfeit any winnings.</p>
            <p>6.6. You acknowledge and agree that all IP Rights, title and interest in and to the Software, including in and to any modification, enhancement, adaptation, translation or other change of or addition to the Software, belong exclusively to or are licensed exclusively to us or our licensors (including Unity or such other provider of gaming software we notify from time to time), even if developed based on ideas, suggestions or proposals by you or any other third party. By accepting this Agreement, you irrevocably assign to us (or to such party as we shall direct) all right, title, and interest you may have or may acquire in and to all such rights, including, without limitation, patent, copyright, trademark, trade secret or know how, and you agree to sign and deliver to us such documents as we or our licensors (including Unity) consider desirable to evidence or effect the assignment of all of the aforesaid rights to us or our licensors. You agree not to, directly or indirectly, attempt to invalidate for any reason whatsoever, or assert, or assist the assertion by others, that the rights, title or interest in the Software belong to any third party (other than our permitted licensors), or that they infringe the IP Rights of others.&nbsp;</p>
            <h3>7. Disclaimer Of Warranties&nbsp;</h3>
            <p>7.1. THE SOFTWARE AND THE APPLICATION ARE MADE AVAILABLE TO YOU HEREUNDER ON AN &lsquo;AS IS&rsquo; BASIS, WITHOUT ANY UNDERTAKINGS, WARRANTIES OR REPRESENTATIONS, EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE. WE DO NOT GUARANTEE THAT OUR SOFTWARE OR THE APPLICATION, OR ANY CONTENT ON THEM WILL ALWAYS BE AVAILABLE OR BE UNINTERRUPTED. WE MAY SUSPEND OR WITHDRAW OR RESTRICT THE AVAILABILITY OF ALL OR ANY PART OF OUR SOFTWARE AND THE APPLICATION FOR BUSINESS AND OPERATIONAL REASONS. WE WILL TRY TO GIVE YOU REASONABLE NOTICE OF ANY SUSPENSION OR WITHDRAWAL.</p>
            <p>7.2.WE [AND UNITY], AND ALL OF THEIR AFFILIATES AND RELATED PARTIES, HEREBY EXCLUDE AND DISCLAIM ANY AND ALL IMPLIED TERMS, CONDITIONS AND WARRANTIES (INCLUDING ANY WARRNATY OF MERCHANTABILITY, SATISFACTORY QUALITY AND FITNESS FOR ANY PARTICULAR PURPOSE), AND, WITHOUT LIMITING THE GENERALITY OF THE AFORESAID, WE AND UNITY DO NOT WARRANT, AMONG OTHER THINGS, THAT (A) THE SOFTWARE WILL BE NON-INFRINGING (B) THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT ANY DEFECTS IN THE SOFTWARE WILL BE CORRECTED, OR THAT THE SOFTWARE IS VIRUS-FREE (C) THE SOFTWARE IS OF SATISFACTORY QUALITY OR FIT FOR ANY PARTICULAR PURPOSE; OR (D) USE BY YOU OF THE SOFTWARE WITH ANY OTHER SOFTWARE, OR WITH INAPPROPRIATE HARDWARE, WILL NOT CAUSE ANY DISTURBANCE TO THE SOFTWARE OR TO SUCH OTHER SOFTWARE.</p>
            <p>7.3. IN THE EVENT THAT A CASH GAME ENDS PREMATURELY DUE TO A FAILURE OR MALFUNCTION OF YOUR EQUIPMENT OR TECHNOLOGY OR YOUR INTERNET SERVICE PROVIDER (INCLUDING LOSS OF SIGNAL, WIRELESS NETWORK CONNECTIONS OR MOBILE DEVICE FAILURE) THEN YOUR ENTRY FEE FOR THAT CASH GAME WILL BE FORFEITED AND BE TAKEN BY YOUR OPPONENT AS A PRIZE. IF A CASH GAME ENDS PREMATURELY DUE TO A FAILURE OR MALFUNCTION OF ANOTHER PLAYER&rsquo;S EQUIPMENT OR TECHNOLOGY OR THEIR INTERNET SERVICE PROVIDER THAT PLAYER WILL BE DEEMED TO HAVE LOST AND FORFEITED THEIR ENTRY FEE. IF A CASH GAME ENDS PREMATURELY AS A RESULT OF OUR NEGLIGENCE, YOUR ENTRY FEE FOR THE CASH GAME AFFECTED WILL BE REFUNDED TO YOUR PLAYER ACCOUNT PENDING AN INVESTIGATION AND THE REFUND WILL REPRESENT OUR MAXIMUM LIABILITY TO YOU.</p>
            <p>7.4. IN THE EVENT OF COMMUNICATIONS OR SYSTEM ERRORS OCCURING IN CONNECTION WITH THE SOFTWARE, NEITHER WE NOR UNITY NOR THEIR AFFILIATES AND RELATED PARTIES WILL BE LIABLE TO YOU OR TO ANY THIRD PARTY FOR ANY COSTS, EXPENSES, LOSSES OR CLAIMS ARISING OR RESULTING FROM SUCH ERRORS.</p>
            <p>7.5. NEITHER WE NOR OUR AFFILIATES AND RELATED PARTIES WILL BE LIABLE TO YOU OR TO ANY THIRD PARTY FOR PAYMENTS MADE (OR NOT MADE) TO YOU AS A RESULT OF A DEFECT OR ERROR IN THE SOFTWARE, OR IN CONNECTION WITH ANY CLAIM OR DEMAND MADE BY UNITY OR ANY THIRD PARTY FOR THE RETURN OF SUCH PAYMENTS OR OTHERWISE IN CONNECTION WITH SUCH PAYMENTS.</p>
            <h3>8. Confidentiality</h3>
            <p>The Software includes non-public and confidential information, which is secret and valuable to us and/or Unity. You agree, as long as you use the Software and thereafter, to (a) keep all such confidential information strictly confidential; (b) not to disclose such confidential information to a third party, and not to use such confidential information for any purpose other than participating in the Online Games. You further agree to take all reasonable steps at all times to protect and keep confidential such confidential information.&nbsp;</p>
            <h3>9. Changes to this Agreement&nbsp;</h3>
            <p>9.1. We may make changes to this Agreement at any time, at our sole discretion. Such changes will take effect from the date specified by us on the Application, whether or not we have notified you specifically of such changes. It is important, therefore, that you log in to the Application from time to time to check to see whether there is a notification of change. Without limiting the generality of the preceding sentence, we may add and remove countries and regions from the list of Restricted Territories and the restrictions in clause 6.3 shall apply to any country or region that becomes a Restricted Territory subsequent to your registration.&nbsp;</p>
            <p>9.2. You agree to be solely responsible for becoming informed of such changes. If you continue to use the Software or the Online Games after the effective date of certain changes (regardless of the way we have notified such changes), you agree to be bound by those changes whether or not you have had actual notice of, or have read, the relevant changes. If you do not agree to be bound by relevant changes, you should not continue to use the Software or the Online Games any further.</p>
            <h3>10. Term and Termination</h3>
            <p>10.1. This Agreement is effective, and binding upon you, from the moment of your acceptance (including when you click the &ldquo;I agree&rdquo; box), and shall remain in force unless terminated in accordance with the provisions hereof.&nbsp;</p>
            <p>10.2. You may terminate this Agreement with by giving us 24 hours notice at any time, subject to the terms of Section 10.4. Termination by you shall be effected by sending us written notice of the termination of your participation on the Application and the Online Games and closure of your account with us.&nbsp;</p>
            <p>10.3. We may terminate this Agreement or suspend or modify your access to the Application, immediately and without prior notice, for any reason at our sole discretion.</p>
            <p>10.4. Upon any termination of this Agreement, whether by us or by you, you agree and acknowledge that (i) your rights to use the Software shall immediately terminate, and (ii) you will cease any and all use of the Software, and (iii) you will remove the Software from your computer, hard drives, networks and other storage material. If we terminate your use of the Application other than pursuant to clause 10.7 below, we will notify you by email using the email address provided to us by you in your Player Account. In such circumstances, we shall (as soon as reasonably practicable) refund the balance held on the Player Account to you (using the Credit Card or Bank Account details provided to us by you), after deduction of entry fees for any Cash Games you have already entered.</p>
            <p>10.5. We shall be entitled immediately to suspend the relevant Player Account, and your use of the Application, if we believe that you do not meet the requirements set out in clauses 3.2.1, 3.2.2, 3.2.3, 3.2.4 and 3.2.5 or, where you use the Software in connection with any Cash Games, we believe that you do not meet the requirements set out in clauses 3.3.1 and 3.3.2. In addition, we shall be entitled immediately to suspend the relevant Player Account, and the your use of the Application, if we believe that:</p>
            <p>10.5.1. you have provided inaccurate, false or misleading information as part of or in connection with your&nbsp;</p>
            <p>Player Account or otherwise in connection with the Application, the Online Games and the services available through it; are involved in any fraud-related activities; or are in breach of any other material provision of this Agreement; or</p>
            <p>10.5.2. any details of the Bank Account or Credit Card used to deposit money into the relevant Player Account were, or have become, incorrect or payment by your Bank Account or Credit Card is contested or is reported as lost or stolen or becomes the subject of fraud; or</p>
            <p>10.5.3. you fail to provide us with Valid Identification Information within five (5) calendar days from when we request it from you.</p>
            <p>10.5.4. any direct debit collection due from you is returned for reasons attributable to you; or</p>
            <p>10.5.5. you have allowed a third party to play Online Games using your Player Account.</p>
            <p>10.6. During the period of any suspension of a Player Account:</p>
            <p>10.6.1. You will be prevented from accessing or using that Player Account; and</p>
            <p>10.6.2. we may investigate the event that gave rise to the suspension and we will be entitled (but shall not be obliged) to require that you provide (in person, if requested by us) all such identification documents as we reasonably require in order to satisfy ourselves as to these matters.</p>
            <p>10.7. If we determine, in our sole discretion, that the event giving rise to suspension has occurred, we will be entitled to terminate the Player Account in question, and all outstanding sums deposited in connection with that Player Account will be forfeited and donated to the charity (except where the sums deposited where deposited by a player who is under 18 years old, in which case the sums deposited will be returned to that person's Player Account, or by any other means available to us).&nbsp;</p>
            <p>10.8. If we determine, in its reasonable discretion, that such a breach has not occurred, the suspension of the Player Account will be brought to an end.</p>
            <h3>11. Limitation of Liability and indemnity</h3>
            <p>11.1. You understand and agree that we will be solely responsible to you under this agreement, and while your commitments under this agreement are also for the benefit of Unity, its affiliates and related parties (and can therefore be enforced by them too), Unity, its affiliates and related parties are not parties to this agreement and will not be liable for any damages of any kind whatsoever caused to you or any third party, regardless of the form of action, whether in contract, tort (including negligence), strict liability or otherwise.&nbsp;</p>
            <p>11.2. You are free to choose whether to download and use the Software and you understand that there is a risk of losing money when using the Software to play Cash Games. If you use the Software, you acknowledge that you do it with the full understanding of this Agreement, including the provisions of this Section 11, and at your own risk. We shall be liable as expressly provided in this Agreement, but shall have no other obligation, duty or liability whatsoever in contract, tort (including negligence), breach of statutory duty or otherwise.</p>
            <p>11.3. Nothing in these terms shall exclude or restrict our liability for death or personal injury resulting from our negligence or for any fraud.</p>
            <p>11.4. Without limiting our obligation to pay, transfer or credit Winnings or Prizes to you in accordance with clause 5.3 above where you are eligible to receive them:&nbsp;</p>
            <p>11.4.1. Our liability to you at any given time shall not exceed an amount equal to:</p>
            <p>11.4.1.1. Where our liability relates to a Cash Game, the aggregate of the entry fees deposited by you in respect of the Cash Game in respect of which our liability has arisen;</p>
            <p>11.4.1.2. Where our liability relates to the misapplication of funds, the amount of money which was your account which has been misplaced by us; and</p>
            <p>11.4.1.3. In respect of any other liability we may have to you, an aggregate of one thousand pounds sterling (&pound;1,000)]; and</p>
            <p>11.4.2. We will not be liable you or anyone else, whether in contract, tort (including negligence), breach of statutory duty or otherwise;&nbsp;</p>
            <p>11.4.2.1. any consequential, incidental or special damage or loss of any kind (including any loss of income, business, anticipated savings or profits); or</p>
            <p>11.4.2.2. without limiting the generality of clause 11.4.2.1, any loss or damage that may arise from any aspect of the Application or the Software or its availability or functionality not within our control; or</p>
            <p>11.4.2.3. any Force Majeure Event:</p>
            <p>11.4.2.4. delays, losses, errors or omissions in or made by the banking system; or</p>
            <p>11.4.2.5. failure or malfunction of the equipment or technology of the relevant player or his/her internet service provider including loss of signal, wireless network connections or mobile device failure; or</p>
            <p>11.4.2.6. for any loss caused by any unauthorised use by a third party of your Bank Account or Credit Card or other method of payment; or</p>
            <p>11.4.2.7. any loss that could not have been reasonably expected by you and us at the time of entering into this agreement howsoever caused or arising, whether through non-supply or late supply of the Application or any service available through the Application, nonperformance of the Application or otherwise.&nbsp;</p>
            <p>11.5. You will, at your own cost and expense, indemnify and hold us and our directors, officers, employees and agents harmless from and against any and all claims, disputes, liabilities, judgments, settlements, actions, debts or rights of action, losses of whatever kind, and all costs and fees, including reasonable legal and attorneys' fees, arising out of or relating to (i) your breach of this Agreement (including any false representations or breach of the warranties in clause 3.2 and 3.3); (ii) any use of your Player Account, the Application, the Software and the associate services by any person including yourself; (iii) your violation of Applicable Laws; and/or (iv) your negligence or misconduct; and, if we instruct you in writing, you will, at your cost and expense, defend us from any of the foregoing using counsel reasonably acceptable to us</p>
            <p>11.6. Nothing in this agreement shall affect your statutory rights (which include, for example, that we will provide our services to a reasonable standard and within a reasonable time). For more information about your statutory rights, contact your local Citizens Advice Bureau, trading standards office or local equivalent.</p>
            <p>11.7. The provisions of this clause 11 shall survive the termination or expiry of this Agreement.</p>
            <h3>12. Reservation of Rights</h3>
            <p>12.1. We reserve, at our sole discretion, the right to:</p>
            <p>12.1.1. change, suspend, remove, modify or add any game on the Online Games;</p>
            <p>12.1.2. collect location data and monitor the location from which you access the Application and require you to have any relevant geo-location feature enabled on your device as a condition precedent of entering any Cash Game.&nbsp;</p>
            <p>12.2. We may at any time disclose certain personal information of yours to third parties in accordance with our Privacy Policy.&nbsp;</p>
            <h3>13. Settlement of Disputes</h3>
            <p>13.1. We are responsible only for those aspects of the Cash Games relating directly to your Player Account on the Application, such as Winnings and/or withdrawals and deposits. We are not responsible for any dispute relating to gameplay. Such disputes should be referred directly to us using the customer service contact information they provide.</p>
            <p>13.2. In the first instance, any disputes should be referred to our customer services team for resolution by emailing <a href='mailto:support@geniegaming.com'>support@geniegaming.com</a> Then our internal review procedure will be used to investigate a complaint from you. We will keep you up to date with our investigations. We will deal with all complaints as soon as reasonably practicable.</p>
            <p>13.3. Disputes should be referred to us as soon as possible and not later than 24hrs after the incident relating to the relevant dispute. When the dispute is open the user is required to provide the crash report for the device</p>
            <h3>14. Acceptable Use</h3>
            <p>14.1. You may only use our Application and our Software for lawful purposes.</p>
            <p>14.2. You may not use our Application and our Software:</p>
            <p>14.2.1. in a way that breaches any Applicable Laws: or</p>
            <p>14.2.2. to commit fraud; or</p>
            <p>14.2.3. to send, receive, upload, download, use or re-use any material that doesn't meet our content standards as notified by us from time to time; or</p>
            <p>14.2.4. to upload obscene, lewd, slanderous, pornographic, abusive, violent, insulting, indecent, threatening and harassing language of any kind, as determined by us in our sole</p>
            <p>discretion;</p>
            <p>14.2.5. to impersonate or deceive another user for the purposes of illicitly obtaining passwords, account information;</p>
            <p>14.2.6. to transmit or procure unsolicited advertising or promotional material; or</p>
            <p>14.2.7. to transmit, send or upload any harmful programs or code designed to affect the operation of computer software or hardware.</p>
            <p>14.3. You agree not to access without authority, damage and/or disrupt our Application, Software, equipment, network, or any equipment, network or software owned or used by any third party.</p>
            <h3>15. Publicity</h3>
            <p>We reserve the right to publicize and promote details of Cash Games and the winners of those Cash Games. We may from time to time publish the name and geographical location by country of Cash Games/and the winners of those Cash Games and a condition of this Agreement is that you agree to us including these details on our Application and/or website and related socialmedia channels if you are a winner. All media enquiries regarding the Application or the Online Games received by you must be referred to us immediately.</p>
            <h3>16. General Provisions</h3>
            <p>16.1. <strong>Third party websites</strong>. You may be able to access third-party websites or services via the Software, Application or our website. We are not responsible for third-party websites, services, or content available through those third-party services. You are solely responsible for your dealings with third-parties (including advertisers and game developers). Your use of thirdparty software, websites or services may be subject to that third-party's terms and conditions</p>
            <p>16.2. <strong>Governing Law</strong>. The construction, validity and performance of this Agreement will be governed by the laws of England.&nbsp;</p>
            <p>16.3. <strong>Competent Courts</strong>. Any legal proceedings arising out of or relating to this Agreement will be subject to the jurisdiction of the courts of London, England. However, this shall not prevent us from bringing any action in the court of any other jurisdiction for injunctive or similar relief.</p>
            <p>16.4. <strong>Severability</strong>. The illegality, invalidity or enforceability of any part of this agreement will not affect the legality, validity or enforceability of the remainder.&nbsp;</p>
            <p>16.5. <strong>Language</strong>. The English language version of this Agreement will prevail over any other language version issued by us.</p>
            <p>16.6. <strong>No assignment by you</strong>. You are not allowed to assign this agreement or any rights or obligation hereunder to any other party.&nbsp;</p>
            <p>16.7. <strong>No waiver</strong>: Any omission to exercise, or delay in exercising, any right or remedy under this Agreement shall not constitute a waiver of that, or any other, right or remedy. The waiver by you are us of any of our rights or remedies arising under these terms and conditions or by law shall not constitute a continuing waiver of that right or remedy or a waiver of any other right or remedy.</p>
            <p>16.8. <strong>Priority</strong>. This agreement shall prevail in the event of any conflict between the terms of this Agreement and any other agreement or document referred to herein or used in connection with the Software.&nbsp;</p>
            <p>16.9. <strong>Severance</strong>: if any provision of this Agreement is held to be invalid or unenforceable by any judicial or other competent authority, all other provisions of this Agreement will remain in full force and effect and will not in any way be impaired. If any provision of this Agreement is held to be invalid or unenforceable but would be valid or enforceable if some part of the provision were deleted, the provision in question will apply with the minimum modifications necessary to make it valid and enforceable.</p>
            <p>16.10. <strong>Third Party Rights</strong>: A person who is not a party to this Agreement shall not have any rights under or in connection with it by virtue of the Contracts (Rights of Third Parties) Act 1999 save that it is agreed that this Agreement is intended to confer a benefit on both us and Unity by making the intellectual property provisions at clause 6) the disclaimer of warranties (at clause 7) and the exclusions and limitations of liability (at clause 11) available to them in accordance with this Agreement provided that the rights of Unity under this Agreement shall only be enforceable by us on their behalf.</p>
            <p>16.11. <strong>Entire agreement</strong>: This Agreement (and any document referred to in it) constitutes the whole Agreement between the parties and supersedes all previous Agreements between the parties relating to its subject matter. In entering into this Agreement you agree you have not relied on, and shall have no right or remedy in respect of, any statement, representation, assurance or warranty (whether made negligently or innocently) other than as expressly set out in this Agreement.&nbsp;</p>
            <p>16.12. <strong>No Partnership:</strong> nothing in this Agreement is intended to, or shall be deemed to, establish any partnership or joint venture between the parties, constitute either party the agent of the other, nor authorise a party to make or enter into any</p>
            <p>commitments for or on behalf of the other party</p>
            <p>16.13. <strong>Notices</strong>. You agree to receive communications from us in an electronic form. Electronic communications may be posted on the pages within the Application or the messages/help files of your client application, or delivered to your e-mail address. All communications in email will be considered to be in &lsquo;writing&rsquo; and to have been received on the earlier of (i) the time a return receipt is generated automatically by the recipient&rsquo;s email server or (ii) the time the recipient acknowledges receipt or (iii) 24 hours after transmission unless the sender receives notification that the email has not been successfully delivered, except that if deemed receipt would occur before 9.00 am GMT on a business day, it shall instead be deemed to occur at 9.00 am on that day and if deemed receipt would occur after 5.00 pm GMT on a business day, or on a day which is not a business day, it shall instead be deemed to occur at 9.00 am GMT on the next business day. Any notices required to be given in writing to us or any questions concerning this agreement should be addressed to <a href='mailto:support@geniegaming.com'>support@geniegaming.com</a>. Neither us or you may use email as a valid means of serving on the other party any (a) notice of breach of this agreement; and (b) legal or court document including the service, delivery or notification of any claim form, notice, order, judgement</p>
            <p>of other document relating to or in connection with any proceedings, suit or action arising out of or in connecting with this Agreement.</p>
            <h3>17. Definitions and Interpretation</h3>
            <p>17.1. The following words and terms, when used in this Agreement, shall have the following meanings, unless the context clearly indicates otherwise:&nbsp;</p>
            <p>&ldquo;<strong>Agreement</strong>&rdquo; the terms and conditions that govern the relationship between you and us, being this end user licence agreement as the same is updated from time to time.</p>
            <p>&ldquo;<strong>Application</strong>&rdquo; means the application software comprised of the Software developed for operation on the iOS operating system, and any related applications and websites on which the Online Games are accessible via links or any other access way.&nbsp;</p>
            <p>&ldquo;<strong>Applicable Laws</strong>&rdquo; means the laws and regulations of the jurisdiction(s) in which you are resident;</p>
            <p>&ldquo;<strong>Assistance Programs</strong>&rdquo; means any artificial intelligence including, without limitation, &lsquo;robots&rsquo; and/or any other computer generated program used to interact with the Software in aid or in place of a player.&nbsp;</p>
            <p>&ldquo;<strong>Bank Account</strong>&rdquo; means the bank account held by you or and linked to the Player Account.</p>
            <p>&ldquo;<strong>Cash Games</strong>&rdquo; any Online Games that require an entry paid in pounds sterling.&nbsp;</p>
            <p>&ldquo;<strong>Credit Card</strong>&rdquo; means any kind of card providing payment, debit, credit and/or similar functions.</p>
            <p>&ldquo;<strong>Force Majeure Event</strong>&rdquo; means any cause affecting the performance of our obligations under this Agreement arising from acts, events, omissions beyond its reasonable control, including acts of God, riots, war, acts of terrorism, fire, flood, storm or earthquake and any disaster and including (a) any power cut and/or failure or obstruction of any network, broadcasting or telecommunications service or (b) the failure of, or damage or destruction to, or any errors caused by any computer systems or records (including, without limitation, the application), or any aspect of such computer systems or records.</p>
            <p>&ldquo;<strong>IP Rights</strong>&rdquo; means any and all intellectual property rights, of all types or nature whatsoever, including, without limitation, patent, copyright, design rights, trade marks, data base rights, applications for any of the above, moral rights, know-how, trade secrets, domain names, URL, trade names or any other intellectual or industrial property rights (and any licenses in connection with any of the same), whether or not registered or capable of registration, and whether subsisting in any specific country or countries or any other part of the world.</p>
            <p>&ldquo;<strong>Online Games</strong>&rdquo; means the online gaming challenges, that we may offer through the Application from time to time (including, but not limited to the Cash Games, online skill based pool games and any other games) and related services and gaming activities offered on the Application.&nbsp;</p>
            <p>&ldquo;<strong>Player Account</strong>&rdquo; means a personal account opened by an individual and maintained with us to enable that person to play the Online Games;</p>
            <p>&ldquo;<strong>Privacy Policy</strong>&rdquo; the policy at which is set out in full at <u><a href='http://www.geniegaming.com/privacy-policy'>www.geniegaming.com/privacy-policy</a></u> established by us in respect of the use, storage and disclosure of the personal information about you or prospective player, as such policy may be amended from time to time.</p>
            <p>&ldquo;<strong>Prize</strong>&rdquo; or &ldquo;<strong>Winnings</strong>&rdquo; prizes, winnings and other representations of value (including, without limitation, real cash, [digital trophies, virtual currency and virtual goods]) and the terms shall be used interchangeably.</p>
            <p>&ldquo;<strong>Restricted Territories</strong>&rdquo; a territory where, at the time of registration, we exclude or prohibit residents from accessing the Application and the Software and Cash Games comprised in it, including but not limited to the countries specified in the schedule to this Agreement and/or as are listed on the Application, in each case as amended from time to time.&nbsp;</p>
            <p>&ldquo;<strong>Software</strong>&rdquo; means the software required to be downloaded, accessed or otherwise utilized by you from the Application for the purpose of participating in the Online Games, including the related documentation and including any enhancements, modifications, additions, translations or updates to such software.</p>
            <p>&ldquo;<strong>us</strong>&rdquo;, &ldquo;<strong>we</strong>&rdquo;, &ldquo;<strong>our</strong>&rdquo; and similar terms means Robert Edgar of Ingleboro House, St Helen&rsquo;s Lane, Corbridge, Northumberland, NE45 5JD trading as &ldquo;Genie Gaming&rdquo;.&nbsp;</p>
            <p>&ldquo;<strong>Username</strong>&rdquo; and &ldquo;<strong>Password</strong>&rdquo; means the username and password chosen by you at the point of registration (subject to any subsequent variations permitted by us), that shall be used to carry out all deposit and withdrawal transactions via the Player Account and that are intended to ensure that you can be uniquely identified by us.</p>
            <p>&ldquo;<strong>Valid Identification Document</strong>&rdquo; a valid identification document in such format as we shall request (including an ID-card, drivers licence, utility bill or passport) which at least shows (as applicable) the your name, current residential address and date of birth</p>
            <p><strong>you</strong>&rdquo;, &ldquo;<strong>your</strong>&rdquo; and similar terms mean the user of the Software downloaded in the Application</p>
            <p>17.2. In this Agreement the following rules of interpretation shall apply:</p>
            <p>17.2.1. The headings in this Agreement are for convenience only and are not for the purpose of interpretation.</p>
            <p>17.2.2. Any reference in this Agreement to any provision of a statute shall be construed as a reference to that provision as amended, re-enacted or extended at the relevant time.</p>
            <p>17.2.3. A reference to a statute or statutory provision shall include all subordinate legislation made from time to time under that statute or statutory provision.</p>
            <p>17.2.4. Subject to clause 16.10 which specifies that contractual notices may not be served by email, a reference to &lsquo;writing&rsquo; or &lsquo;written&rsquo; includes emails (but not faxes).</p>
            <p>17.2.5. Unless the context otherwise requires, words in the singular shall include the plural and in the plural shall include the singular.</p>
            <p>17.2.6. Any obligations on a party not to do something includes an obligation not to allow that thing to be done.</p>
            <p>17.2.7. Any words following the terms including, include, for example or any similar expression shall be construed as illustrative and shall not limit the sense of the words, description, definition, phrase or term preceding those terms.</p>
            <p>17.2.8. References to clauses are to clauses of this Agreement, unless stated otherwise.</p>
            <p>17.2.9. A person includes a natural person, corporate or</p>
            <p>unincorporated body (whether or not having separate legal personality).</p>
            <h3>RESTRICTED TERRITORIES</h3>
            <p>We are aiming to initially release 8 Ball Pool Real Cash in the UK only, if the app proves to be as successful as we anticipate, we hope to work together with the payment provider to look into other accessible regions.</p>
            <p>In order to validate the user&rsquo;s location in 8 Ball Pool Real Cash, to verify that they are in a region which allows skill based gaming, we will use the following method. The user will be able to open the app and play in the practice room. We will first ask the user to enable location based services on their device when they try to deposit money or when they try to open a room which requires an entry fee.</p>
            <p>We will show a loading screen while we detect their location, then send that location to our server which will validate that it is not a region where we can not operate. If the server returns with a response indicating the user is in a restricted region, we will show an error and send them back to the home page. If the server says they are in a region where skill based gaming is allowed, we will proceed to the original intended screen.</p>
            <p>Genie Gaming will continue to liaise with the payment provider in order to ensure both parties can operate in specific territories.</p>

        ";

        $data = [
            'content' => $content,
            'facebook' => $this->facebook,
            'instagram' => $this->instagram,
            'twitter' => $this->twitter,
        ];

        return view('pages.info', $data);
    }
}
